### ISSUE TITLE
Find All in SikuliX api of java not working correctly

### ISSUE THREAD

**Issue by umsalotagi** [RaiMan/SikuliX-2014#123] opened 2015-04-17 11:49 UTC
Find all feature is not working well. It is giving wrong results. The find feature whereas works very well but the same pattern is not recognized by find all. This pattern recognition fails very badly if there is some unplanned mouse movement just before execution of find all. The same feature works very well in sikuli IDE. but for sikulix api of java, this feature fails.

**Comment by umsalotagi** [comment] 2015-04-17 11:56
Please note that findAll feature does not fail all time. But its behavior is completely unpredictable. Sometimes it works find, while sometimes it fails miserably.

**Comment by RaiMan** [comment] 2015-04-17 13:46
What version of SikuliX are you talking about?

Could you be a bit more specific with the problems you have?

any examples?

**Comment by umsalotagi** [comment] 2015-04-20 04:50
I am working on sikuli in Maven using .pom provided on Sikuli official web site. Working on sikulixapi-1.1.0. built on (16 March 2015). I want to select particular button in the drop-down [v]. So I decided to use FindAll to iterate all the drop-down on the screen and select the correct button from one of the drop-down. I saved the image of drop-down like this [v]. I used FindAll . 
For first 10-15 replay it worked very fine, It found all the drop-down on screen and iterated through it. But when I go to show this to my manager it failed. It started clicking anywhere on screen (not on drop-down image). This is behaving unpredictably. Sometimes it works very well, and many times it fails and clicks somewhere else. I replayed it many times, result is unpredictable.:(

**Comment by RaiMan** [comment] 2015-04-20 08:41
Did you show it on your own machine or any other machine?

possible to get a screenshot of the failing case and the Image you use.

at least paste the relevant code here, to see how you are using the Feature.

**Comment by umsalotagi** [comment] 2015-04-21 06:31
Yes I showed it on my machine. I cant post any image of product I am working. But code is like this:
Code is very basic 
import org.sikuli.script.Region;
....
..
..
Iterator<Match> iterator;
iterator = r.findAll("drop-down image path"); // r is region 
while (iterator.hasNext()) {
     r.click(iterator.next());	 // click on drop-down
     if (r.exists("button image path")!=null) {  // checks whether the button image present in drop-down
          r.click("button image path");
          break;
     }
}

This code runs sometimes perfectly. click on the drop-down correctly, but many times it fails. instead of   clicking on drop-down it click on somewhere else in unpredictable manner.

**Comment by RaiMan** [comment] 2015-04-21 07:11
r.click(iterator.next()); // click on drop-down
I guess after this the dropdown opens. this usually take some time or is somehow animated, which in turn takes time.
Since you are using the same region r for the button search, the following might happen:
- the first search starts some milliseconds after the click
- the dropdown is not yet (fully) open
- the search finds something similar to "button image path" in the region r and finishes (still the dropdown might not be fully open)

what can you do?
- use Pattern and raise minimum similarity to avoid false positives
- restrict the region to the smaller area, where you expect the dropdown to appear.

To have more options for debugging and optimisations:

```
//Debug.on(3) // uncomment to switch on verbose debug output
matches Iterator <Match> = r.findAll("drop-down image path"); // r is region 
Pattern pButton = new Pattern("button image path").similar(0.9);
Match mButton;
while (matches.hasNext()) {
    Match m = iterator.next(); // m now could be inspected with debugging
    r.click(m); // click on drop-down
    if ((mButton = r.exists(pButton))!=null) { // checks for button image and saves the match
        r.click(mButton); // just click the match, do not search again
        break;
    }
}
//Debug.off() // uncomment to switch off debug 
```

**Comment by umsalotagi** [comment] 2015-04-21 11:44
It fails in detecting the Drop-down image. As I said earlier problem in find-all. instead of clicking on drop-down image it clicks on somewhere else. Same code when run multiple times on same UI. Sometimes it clicks on drop-down. and many times it clicks somewhere else, instead of drop-down. Behaviuor is unpredictable. Findall feature sometimes returns correct Match ierator of dop-down but many times false. clicks somewhere else. 
In actual application I used pattern with .simillar(0.98)

**Comment by RaiMan** [comment] 2015-04-21 12:04
ok, the 0.98 might be a similarity, that is too high, so depending on the quality of your image (amount of background towards the edges), it just splits between found and failed around 0.98.
So test e.g. with 0.9.

since everything with Sikuli is about RGB-pixels contained in a rectangular screen area and on the other hand it is based on the matchTemplate feature of OpenCV, there are many possible reasons for the fact, that Sikuli finds something else, than expected.
So if Sikuli finds something, but that is not what you expect, then it does not fail and you have to sort out the reason for this not expected behaviour.

So you either send me some images privately, that I can check or you use the above mentioned debugging option. 

That is all I can do for you.

**Comment by RaiMan** [comment] 2015-10-25 18:19
will only be addressed in version 2

**Closed by RaiMan** 2015-10-25 18:19 UTC
